[package]
name = "recover9pl"
version = "0.0.1"
authors = [ "andrewchambers <ac@acha.ninja>" ]
edition = "2021"

[[bin]]
name = "recover9pl"

[dependencies]

getopts = "0.2"
log = "0.4.0"
env_logger = "0.8.4"

[dependencies.p92000l]
path = "../../"
