[package]
name = "lclient"
version = "0.0.1"
authors = [ "andrewchambers <ac@acha.ninja>" ]
edition = "2021"

[[bin]]
name = "lclient"

[dependencies]
nix = "*"

[dependencies.p92000]
path = "../../"
