[package]
name = "roexport"
version = "0.0.1"
authors = [ "andrewchambers <ac@acha.ninja>" ]
edition = "2018"

[[bin]]
name = "roexport"

[dependencies]
nix = "0.18"

[dependencies.p92000l]
path = "../../"

[profile.release]
opt-level = 3
lto = true